# Generated by Django 2.2.16 on 2021-05-20 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easyviewer.models
import jsonfield.fields
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', easyviewer.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default='-ybMJQd7k5J7_6Zb6jyaTfXM7M8nocV8hhg23AyIUsI', max_length=200)),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('disk_size', models.PositiveIntegerField()),
                ('fee', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meta', models.CharField(max_length=500)),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('VAUDEVILLE', 'Водевиль'), ('DRAMA', 'Драма'), ('COMEDY', 'Комедия'), ('MELODRAMA', 'Мелодрама'), ('MIME', 'Мим'), ('MYSTERY', 'Мистерия'), ('MONODRAMA', 'Монодрама'), ('MORALITY', 'Моралите'), ('MUSICAL', 'Мюзикл'), ('PARODY', 'Пародия'), ('PASTORAL', 'Пастораль'), ('SOTI', 'Соти'), ('TRAGEDY', 'Трагедия'), ('TRAGICOMEDY', 'Трагикомедия'), ('FARCE', 'Фарс'), ('Extravaganza', 'Феерия')], max_length=133)),
                ('actors', models.CharField(max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateField()),
                ('duration', models.DurationField()),
                ('image', models.ImageField(upload_to='uploads/image')),
                ('preview_video', models.FileField(upload_to='uploads/preview')),
                ('url', models.CharField(max_length=400)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyviewer.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyviewer.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateTimeField()),
                ('data_end', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyviewer.Video')),
                ('video_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyviewer.VideoSubscriptions')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyviewer.VideoSubscriptions'),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default='7sPKwttuprd2iEpzDf-DbP7Xj-RwBFYYOkUqvhefwlk', max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('P', 'Payed'), ('US', 'Unsuccessful')], default='Active', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('json_description', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='easyviewer.Projects')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='subscription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyviewer.ProjectSubscriptions'),
        ),
        migrations.AddField(
            model_name='projects',
            name='user_id',
            field=models.ManyToManyField(through='easyviewer.AdminProject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminproject',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyviewer.Projects'),
        ),
        migrations.AddField(
            model_name='adminproject',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
