# Generated by Django 2.2.16 on 2021-05-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/image'),
        ),
    ]
