# Generated by Django 2.2.16 on 2021-05-25 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyviewer', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='transaction_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='easyviewer.Transactions'),
            preserve_default=False,
        ),
    ]
