# Generated by Django 2.2.16 on 2021-06-01 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyviewer', '0003_videocontent_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='video_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easyviewer.Video'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='easyviewer.VideoSubscriptions'),
        ),
    ]
