# Generated by Django 2.2.16 on 2021-06-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyviewer', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview_video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
