# Generated by Django 2.2.16 on 2021-06-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyviewer', '0006_auto_20210605_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
