# Generated by Django 2.2.16 on 2021-06-12 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyviewer', '0006_auto_20210605_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosubscriptions',
            name='period_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyviewer.Projects'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videosubscriptions',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
