# Generated by Django 2.2.16 on 2021-08-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyviewer', '0007_auto_20210612_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
