# Generated by Django 2.2.16 on 2022-01-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyviewer', '0008_auto_20210810_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
