name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


    create-envfile:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: GITHUB_WORKSPACE
          run: echo "$GITHUB_WORKSPACE"
        - name: Create .env
          uses: DeveloperRic/action-create-env@v1.0.2
          with:
            full_text: |
              SECRET_KEY=SECRET_KEY
            directory: ${{ github.workspace }}/backend
        - name: Create google1.json
          id: create-json
          uses: jsdaniell/create-json@1.1.2
          with:
            name: "google1.json"
            json: '{"key":"superKey", "password":"super_pass"}'
            dir: '/backend'
        - name: Read package.json
            id: package
            uses: juliangruber/read-file-action@v1
            with:
              path: ./backend/google1.json
              - name: Echo package.json
                run: echo "${{ steps.package.outputs.content }}"

#        - name: Create google1.json
#          uses: schdck/create-env-json@v1
#          id: create-env
#          with:
#            file-name: 'google1.json'
#            full-path: /backend
#            super-secret: 'SuperSecret'
#        - name: Build the Docker image
#          run: docker-compose -f docker-compose-prod.yaml up --build -d
#        - name: Dump GitHub context
#          env:
#            GITHUB_WORKSPACE: ${{ github.workspace }}
#            GITHUB_CONTEXT: ${{ toJson(github.workspace) }}
#          run: echo "$GITHUB_CONTEXT"
#          with:
#            repository: sashproaa/bootcam-video-viewer
#        - name: Make envfile
#          uses: actually-colab/github-action-create-env-file@v2.1
#          with:
#            envkey_DEBUG: 'True'
#            envkey_SWAGGER: 'True'
#            INPUT_ENVKEY_SECRET_KEY: 'SECRET_KEY'
#            envkey_SECRET_KEY: 'SECRET_KEY'
#            envkey_PUBLIC_KEY: 'LIQPAY_PUBLIC_KEY'
#            envkey_PRIVATE_KEY: 'LIQPAY_PRIVATE_KEY'
#            envkey_GOOGLE_APPLICATION_CREDENTIALS: 'GOOGLE_APPLICATION_CREDENTIALS'
#            envkey_EMAIL_HOST_PASSWORD: 'EMAIL_HOST_PASSWORD'
#            directory: backend/src
#            file_name: .env
#        - name: Make google-json-file
#          uses: actually-colab/github-action-create-env-file@v2.1
#          with:
#            envkey_SECRET_KEY: SECRET_KEY
#            directory: backend/src
#            file_name: google1.json
#
#    build:
#
#      runs-on: ubuntu-latest
#
#      steps:
#      - uses: actions/checkout@v2
#      - name: Build the Docker image
#        run: docker-compose -f docker-compose-prod.yaml up --build -d
#      needs: 'create-envfile'
