name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file docker-compose-prod.yaml https://github.com/sashproaa/bootcam-video-viewer/blob/main/docker-compose-prod.yaml
