name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


    build:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: GITHUB_WORKSPACE
          run: echo "$GITHUB_WORKSPACE"
        - name: Create .env  # for commands in Dockerfile
          uses: DeveloperRic/action-create-env@v1.0.2
          with:
            full_text: |
              SECRET_KEY=SECRET_KEY
            directory: ${{ github.workspace }}/backend
        - name: Create google1.json  # for commands in Dockerfile
          id: create-json
          uses: jsdaniell/create-json@1.1.2
          with:
            name: "google1.json"
            json: '{"key":"superKey", "password":"super_pass"}'
            dir: '/backend'
        - name: Read google1.json
          id: package
          uses: juliangruber/read-file-action@v1
          with:
            path: ./backend/google1.json
        - name: Echo package.json
          run: echo "${{ steps.package.outputs.content }}"
        - name: Build the Docker image
          run: docker-compose up --build -d

